### ISSUE TITLE
Bot acting on itself

### ISSUE THREAD

**Issue by Master9000** [ThatNerdyPikachu/Pika.py#1]
if you add the "star" reaction to the bot's message on a #starboard, it will do its star routine again. 
fix should be adding if statement user id != 412042272268615680 before sending a message to starboard

**Comment by ThatNerdyPikachu** [comment]
Either that, or check for the channel.

**Comment by ThatNerdyPikachu** [comment]
This was fixed yesterday, closing issue now.
